name: CI/CD for ML model to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall huggingface_hub
        pip install -r requirements.txt

    - name: Log in to Hugging Face
      run: |
        huggingface-cli login --token ${{ secrets.HUGGINGFACE_API_TOKEN }}
      env:
        HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

    - name: Create Hugging Face Space with Python API
      run: |
        python -c "
        from huggingface_hub import HfApi;
        api = HfApi();
        api.create_repo(
            repo_id='Ml_Model',
            repo_type='space',
            space_sdk='gradio'
        )"

    - name: Push to Hugging Face Space
      run: |
        hf space push . --space-name manahilhassan9603/Ml_Model
