name: CI/CD for ML model to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub
        pip install -r requirements.txt

    - name: Log in to Hugging Face
      run: |
        huggingface-cli login --token ${{ secrets.HUGGINGFACE_API_TOKEN }}
      env:
        HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

    - name: Check if repository exists and create it if not
      run: |
        python -c "
        from huggingface_hub import HfApi
        api = HfApi()
        repo_id = 'manahilhassan9603/Ml-Model'
        try:
            # Attempt to create the repo if it doesn't exist
            api.create_repo(
                repo_id=repo_id, 
                repo_type='space', 
                space_sdk='gradio'
            )
            print(f'Repository {repo_id} created successfully.')
        except Exception as e:
            if '409 Client Error' in str(e):
                print(f'Repository {repo_id} already exists.')
            else:
                raise e
        "
      env:
        HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

    - name: Upload to Hugging Face Space
      run: |
        python -c "
        from huggingface_hub import upload_folder
        upload_folder(
            folder_path='./',
            repo_id='manahilhassan9603/Ml-Model',
            token='${{ secrets.HUGGINGFACE_API_TOKEN }}'
        )"
